# **Python pip**


* Python supports a lot of third-party packages which can be easily installed using pip.
* **pip** is a package installer for python.
* Note that pip is not a python function. It is a command line tool which is used to manage packages in python.

## **Installing a package**

* If you have python installed on your local machine, you can try using pip on your command prompt.

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


* You can find numerous useful python packages at https://pypi.org/

## **Using a package**

* To use a package in python, we need to first import it to our code using the `import` and `from` keyword.



In [ ]:
from math import sqrt
x=3
y=4
z=sqrt(x**2+y**2)
print(z)

5.0


# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

# **Extending Python Using NumPy**

* Due to the way that a Python list is implemented, accessing items in a large list is computationally expensive.

*   The main problem with the list is that, to allow a list to have non-uniform data types, each item in the list is stored in a memory location, with the list containing an "array" of pointers to each of these locations.   
*  In NumPy, an array is of type `ndarray` (n-dimensional array), and all the elements must be of the same type.



# Creating NumPy Arrays

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
a1=np.arange(10) #Created a range from 0 to 9
print(a1)
print(a1.shape)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
(10,)


* To create an array of a specific size filled with 0's, we use the zeros() function.

In [ ]:
a2= np.zeros(5) # Creates an array with all 0's
print(a2)
print(a2.shape)

* We can also create two-dimensional arrays using the zeros() function

In [ ]:
a3=np.zeros((2,3)) #Array with 2 rows and 3 columns; This array has all zeros.
print(a3.shape)
print(a3)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


* If we want an array filled with a specific number instead of 0, use the `full()` function

In [ ]:
a4= np.full((3,3),8)
print(a4)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


* The `eye()` function returns a 2-D array with ones on the diagonal and zeros elsewhere. For eg.

In [ ]:
a5= np.eye(4) # 4x4 identity matrix
print(a5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


* To create an array filled with random numbers, we can use the `random()` function from the `numpy.random` module.

In [ ]:
a6= np.random.random((2,4)) # A 2x4 Array with random values.
print(a6)

[[0.30783556 0.68356903 0.44497482 0.34375784]
 [0.97769958 0.20628799 0.66165133 0.6961044 ]]



# Array Indexing

* Accessing elements in the array is similar to accessing elements in a Python List.

In [ ]:
list1= [1,2,3,4,5]
list2= [6,7,8,9,0]
r1 = np.array([list1,list2])
print(r1)
print(r1.shape) # 2 rows and 5 columns
print(r1[0,0])
print(r1[0,1])

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
2


## Boolean Indexing

In [ ]:
r2=np.array(list1)
print(r2)
print(r2>2) # Prints a list containing boolean values.
print(r2[r2>2]) # [3,4,5]

#Write a code to list all the odd numbers from a list of numbers using boolean indexing.
nums= np.arange(10)
print(nums)
odd_nums = nums[nums%2==1]
print(odd_nums)


## Slicing Arrays

* Very important feature of NumPy, very useful in ML.
* Similar to Python List.

In [ ]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


* Slicing has the syntax: `start:stop`. So for a 2-D array it becomes:  `[start:stop, start:stop]`

In [ ]:
# We will extract the last two rows and the first two columns using slicing.
b1 = a[0:,:2] #row 1 to the last row, and the first 2 columns
print(b1)



[[ 1  2]
 [ 6  7]
 [11 12]]


In [ ]:
#With negative indexing
b2= a[-3:,-5:-3]
print(b2)

Point to Note: Result of slicing is dependent on how you slice it. For eg.


In [ ]:
b3=a[2:,:] # row 2 onwards and all columns.
print(b3)
print(b3.shape) # Here the result is rank 2. # Rank is simply the number of dimensions(or axes) an array has

[[11 12 13 14 15]]
(1, 5)


In [ ]:
b4=a[2,:]
print(b4)
print(b4.shape)

[11 12 13 14 15]
(5,)


## Reshaping the Arrays

* You can reshape the arrays to other dimensions using the `reshape()` keyword.

In [ ]:
b4 = b4.reshape(1,-1) # First arguement indicates the number of rows.
                      # -1 indicates that we leave it to the reshape() function to create the correct number of columns.
                      # You can also specify the number of columns in the second argument
print(b4)
print(b4.shape)

[[11 12 13 14 15]]
(1, 5)


## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example

In [ ]:
# Given a matrix X which is (nx1), we want to make a matrix such that
''' [1, x1, (x1)^2, (x1)^3, ......, (xn)^n
     1, x2, (x2)^2, (x2)^3, ......, (xn)^n
     ...................
     .
     .
     .
     .
     .
     1, xn, (xn)^2, (xn)^3, ......., (xn)^n]
'''
#Give a Brute Force Approach using for l


X = np.array([1,2,3,4,5]).reshape(5,1)
print(X.shape)
pow = np.arange(0,len(X))
mat = X ** pow
print(mat)

(5, 1)
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


## Coding Problem-4


In [ ]:
## Write a program that creates a 3x3 matrix with values ranging from 1 to 9. Then, modify the matrix by doubling the values of the second row.

# Your Code here.

For more examples on python and numpy, you can also go through the following tutorial.

https://cs231n.github.io/python-numpy-tutorial/
